# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='sale',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Auto'),
        ),
    ]
