# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_games', models.IntegerField()),
                ('teams', models.ManyToManyField(to='core.Team')),
            ],
        ),
    ]
